services:
  postgres:
    image: postgres:17
    container_name: aura-x-db
    restart : always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aurax
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
       image: redis:latest
       container_name: aura-x-redis
       ports:
         - "6379:6379" 
       volumes:
        - redis_data:/data

volumes:
  postgres_data:
  redis_data: